services:
  db:
    image: postgres:16
    container_name: usperdidos
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: poli_usp_2026
      POSTGRES_DB: usperdidos
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
